{% set name = "dap" %}
{% set version = "0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  git_url: https://github.com/molinerisLab/dap.git
  git_ref: 0.1

requirements:
  host:
    - pip
    - python
  run:
    - python
    - typer
    - gitpython
    - direnv


about:
  home: https://github.com/molinerisLab/dap
  summary: Bioinformatics projects management tool